networks:
  virtual-stub-network:

services:
  kong:
    image: kong
    networks:
      - virtual-stub-network
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/kong.yml"
      KONG_LOG_LEVEL: debug
    ports:
      - "8000:8000" #Container-port:Host-port
      - "8001:8001" #Container-port:Host-port
    volumes:
      - ./kong.yml:/kong/kong.yml
    healthcheck:
      test: [ "CMD", "curl", "-k", "-f", "http://localhost:8000/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5

  virtual-stub-service-1:
    image: virtual-stub-image
    build: .
    networks:
      - virtual-stub-network
    ports:
      - "8081:8080"
    environment:
      - INSTANCE_ID=instance-1


  virtual-stub-service-2:
    image: virtual-stub-image
    build: .
    networks:
      - virtual-stub-network
    ports:
      - "8082:8080"
    environment:
      - INSTANCE_ID=instance-2
